version: '3.7'

services:
  app:
    container_name: "drupal-repository-webhook"
    image: ghcr.io/city-of-helsinki/drupal-repository:latest
    restart: always
    volumes:
      - .:/app:delegated
      - ./hooks.json:/etc/webhook/hooks.json
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`webhook.drupal.hel.ninja`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=le"
    networks:
      - internal
      - traefik-network
  nginx:
    container_name: "drupal-repository-nginx"
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    networks:
      - traefik-network
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`repository.drupal.hel.ninja`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=8080"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.http.routers.nginx.tls.certresolver=le"

networks:
  internal:
    external: false
  traefik-network:
    external: true
