version: '3.7'

services:
  app:
    container_name: "drupal-repository-webhook"
    image: ghcr.io/city-of-helsinki/drupal-repository:latest
    volumes:
      - .:/app:delegated
      - ./hooks.json:/etc/webhook/hooks.json
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.rule=Host(`helfi-webhook.docker.so`)"
      - "traefik.http.routers.app.tls=true"
      - "traefik.docker.network=stonehenge-network"
    networks:
      - internal
      - stonehenge-network

  nginx:
    container_name: "drupal-repository-nginx"
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    networks:
      - stonehenge-network
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.routers.nginx.rule=Host(`helfi-repository.docker.so`)"
      - "traefik.http.services.nginx.loadbalancer.server.port=8080"
      - "traefik.http.routers.nginx.tls=true"
      - "traefik.docker.network=stonehenge-network"

networks:
  internal:
    external: false
  stonehenge-network:
    external: true
