---
- name: Create a Docker network
  docker_network:
    name: "{{ traefik_network | mandatory }}"
    state: present
  tags:
    - "traefik"

- name: Create Traefik configuration file
  template:
    src: templates/traefik.yml.j2
    dest: /home/traefik.yml
  tags:
    - "traefik"

- name: Check that acme.json exists
  stat:
    path: "/home/acme.json"
  register: acme
  tags:
    - "traefik"

- name: Create /home/acme.json
  file:
    path: "/home/acme.json"
    state: touch
    mode: "0600"
  when: acme.stat.exists == False
  tags:
    - "traefik"

- name: Install and start Traefik
  docker_container:
    name: proxy
    image: "traefik:{{ traefik_version }}"
    state: started
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.httpCatchall.rule: "HostRegexp(`{any:.+}`)"
      traefik.http.routers.httpCatchall.entrypoints: "http"
      traefik.http.routers.httpCatchall.middlewares: "httpsRedirect"
      traefik.http.middlewares.httpsRedirect.redirectscheme.scheme: "https"
      traefik.http.middlewares.httpsRedirect.redirectscheme.permanent: "true"
    published_ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/acme.json:/home/acme.json"
      - "/home/traefik.yml:/traefik.yml:ro"
    networks:
      - name: "{{ traefik_network | mandatory }}"
    networks_cli_compatible: yes
  tags:
    - "traefik"
