name: Build package repository
on:
  push:
    branches:
      - master
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/composer@v2
      - uses: actions/checkout@v2
      - name: Publish packages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          make
          cd dist/
          git commit -am "Package ${GITHUB_SHA}"
          git push
