name: Build packages
on:
  push:
    branches:
      - master
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v2

      - name: Build packages
        run: make

      - name: Commit built package
        run: |
          cd dist/
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Package ${GITHUB_SHA}"
          git push
