name: Tests
on:
    pull_request:
    push:
        branches:
            - 3.x
env:
  GITHUB_OAUTH: $GITHUB_TOKEN
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['8.2']
        steps:

            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP with composer v2
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '${{ matrix.php-versions }}'
                  coverage: pcov
                  tools: composer:v2

            - name: Validate satis.json
              run: cat satis.json | jq type

            - name: Validate composer.json
              run: composer validate

            - name: Install Composer dependencies
              run: composer install --no-progress

            - name: Run installer
              run: make

            - name: Run phpcs
              run: vendor/bin/phpcs src tests --standard=PSR2

            - name: Run phpstan
              run: vendor/bin/phpstan analyze --no-progress

            - name: Run PHPUnit tests
              run: |
                  set -o pipefail && vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v4.0.1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                slug: City-of-Helsinki/drupal-repository
