name: Tests
on:
    pull_request:
    push:
        branches:
            - 3.x
env:
  GITHUB_OAUTH: $GITHUB_TOKEN
  COMPOSER_HOME: /tmp
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-versions: ['8.4']
        steps:

            - name: Checkout code
              uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - name: Setup PHP with composer v2
              uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
              with:
                  php-version: '${{ matrix.php-versions }}'
                  coverage: pcov
                  tools: composer:v2

            - name: Validate satis.json
              run: cat satis.json | jq type

            - name: Validate composer.json
              run: composer validate

            - name: Install Composer dependencies
              run: composer install --no-progress

            - name: Run installer
              run: make

            - name: Run phpcs
              run: vendor/bin/phpcs src tests --standard=PSR2

            - name: Run phpstan
              run: vendor/bin/phpstan analyze --no-progress

            - name: Run PHPUnit tests
              run: |
                  set -o pipefail && vendor/bin/phpunit --coverage-clover=coverage.xml

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                slug: City-of-Helsinki/drupal-repository
